import Head from 'next/head'
import Amenities from '../components/Amenities'
import Header from '../components/Header'
import SearchBody from '../components/SearchBody'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Wheel App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header />

      {/* SearchBody */}

      <SearchBody />

      {/* Amenities */}

      <Amenities />
    </div>
  )
}
